[build]
  command = "hugo --gc --minify --enableGitInfo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.145.0_extended"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.145.0_extended"
  HUGO_ENV = "development"